"""Parser for GDROM v2 rule text files.

Two artifact types are parsed:

- `modules/{grand_id}_{module_id}.txt`: per-module release rules keyed to
  (Inflow, Storage). One of two kinds:
    - EXPR: a single release expression covering the domain.
    - TREE: a sequence of `if (predicates) then Release: <expr>` branches,
      evaluated in file order; first match wins.
- `module_conditions/{grand_id}.txt`: dispatcher CART keyed to
  (Inflow, Storage, PDSI, DOY) that selects which module to apply.

The release expression is an affine function
    Release = a_inflow * Inflow + a_storage * Storage + c
optionally wrapped in `max(..., 0)` to clamp at zero. This accommodates the
full set of release forms observed in GDROM v2:
  - CONSTANT   `Release: 35.0377`                          → (0, 0, 35.0377, -inf)
  - LINEAR     `Release = 1.0230 * Inflow + -3.7865`       → (1.0230, 0, -3.7865, -inf)
  - MULTI-LIN  `Release = 0.9531*I + -0.2061*S + 510.0264` → (0.9531, -0.2061, 510.0264, -inf)
  - MAX-LIN    `Release: max(0.0404 * Storage + 491.72, 0)`→ (0, 0.0404, 491.72, 0.0)
  - NaN        `Release: nan`                              → (nan, nan, nan, -inf)

Empty-predicate branches (`if () then ...`) are retained as zero-predicate
branches; the evaluator treats them as never-matching (mirroring Python's
`if ():` semantics in the `rule2model.py` reference).

Grammar reference: Section 21 of the GDROM v2 technical report (extended to
cover the multivariate and max-clamped forms present in the actual data).
"""

from __future__ import annotations

import ast
import math
import re
from dataclasses import dataclass
from enum import IntEnum
from pathlib import Path


class ModuleKind(IntEnum):
    """Module structure code: one release expression or a predicate tree."""

    EXPR = 0  # single ReleaseExpr covering all inputs
    TREE = 1  # sequence of (predicates → ReleaseExpr) branches


class VarCode(IntEnum):
    """Variable index used in predicate triples; matches input-tuple ordering."""

    INFLOW = 0
    STORAGE = 1
    PDSI = 2
    DOY = 3


class OpCode(IntEnum):
    """Comparison operator code used in predicate triples."""

    LE = 0  # <=
    LT = 1  # <
    GE = 2  # >=
    GT = 3  # >


_VAR_CODES: dict[str, VarCode] = {
    "Inflow": VarCode.INFLOW,
    "Storage": VarCode.STORAGE,
    "PDSI": VarCode.PDSI,
    "DOY": VarCode.DOY,
}
_OP_CODES: dict[str, OpCode] = {
    "<=": OpCode.LE,
    "<": OpCode.LT,
    ">=": OpCode.GE,
    ">": OpCode.GT,
}


@dataclass(frozen=True, slots=True)
class PredicateTriple:
    """One (var, op, threshold) comparison inside a rule predicate clause."""

    var_code: VarCode
    op_code: OpCode
    threshold: float


@dataclass(frozen=True, slots=True)
class ReleaseExpr:
    """Affine release: `max(a_inflow*Inflow + a_storage*Storage + c, clamp_min)`.

    `clamp_min = -inf` encodes "no clamp"; `clamp_min = 0.0` encodes the
    `max(..., 0)` wrapper seen in some Res_M modules. Any other clamp value is
    reserved for future use.
    """

    a_inflow: float
    a_storage: float
    c: float
    clamp_min: float

    def evaluate(self, inflow: float, storage: float) -> float:
        """Evaluate the release for one time step.

        Parameters
        ----------
        inflow : float
            Reservoir inflow.
        storage : float
            Reservoir storage.

        Returns
        -------
        float
            Release, clamped at ``clamp_min`` when it is finite.
        """
        v = self.a_inflow * inflow + self.a_storage * storage + self.c
        if math.isfinite(self.clamp_min):
            return max(v, self.clamp_min)
        return v


@dataclass(frozen=True, slots=True)
class ModuleBranch:
    """One branch of a TREE module: predicates → release expression."""

    predicates: tuple[PredicateTriple, ...]
    release: ReleaseExpr


@dataclass(frozen=True, slots=True)
class ModuleDescriptor:
    """Parsed contents of one `modules/{grand_id}_{module_id}.txt` file.

    For EXPR kind, `expr` is populated and `tree_branches` is empty.
    For TREE kind, `tree_branches` is populated and `expr` is None.
    """

    grand_id: int
    module_id: int
    kind: ModuleKind
    expr: ReleaseExpr | None = None
    tree_branches: tuple[ModuleBranch, ...] = ()


@dataclass(frozen=True, slots=True)
class ConditionBranch:
    """One branch of a dispatcher CART: predicates → module_id.

    Empty `predicates` means the branch never matches (mirrors `if ():` in
    Python, as generated by rule2model.py for `if ()` source lines).
    """

    predicates: tuple[PredicateTriple, ...]
    module_id: int


@dataclass(frozen=True, slots=True)
class ConditionDescriptor:
    """Parsed contents of one `module_conditions/{grand_id}.txt` file.

    Branches are evaluated in file order; first match wins.
    """

    grand_id: int
    branches: tuple[ConditionBranch, ...]


# --- Regex grammar -----------------------------------------------------------

_NUM = r"-?\d+(?:\.\d+)?|nan"  # plain float or the NaN literal
_VAR_GROUP = "|".join(_VAR_CODES)
_OP_GROUP = "<=|>=|<|>"  # order matters: longest first
_EXPR = r".+"  # permissive; validated downstream via AST

_RE_MODULE_EXPR_RELEASE = re.compile(rf"^Release\s*=\s*({_EXPR})$")
_RE_MODULE_CONST_RELEASE = re.compile(rf"^Release\s*:\s*({_EXPR})$")
_RE_TREE_BRANCH = re.compile(rf"^if\s*(.*?)\s*then\s+Release\s*:\s*({_EXPR})$")
_RE_CONDITION_BRANCH = re.compile(r"^if\s*(.*?)\s*then\s+module\s*:\s*(\d+)\s*$")
_RE_PREDICATE = re.compile(rf"\(\s*({_VAR_GROUP})\s*({_OP_GROUP})\s*({_NUM})\s*\)")


class RuleParseError(ValueError):
    """Raised when a rule file cannot be parsed per the documented grammar."""


# --- Release-expression parser ----------------------------------------------

_RE_MAX_WRAP = re.compile(r"^max\s*\(\s*(.+?)\s*,\s*0(?:\.0+)?\s*\)\s*$")

_ALLOWED_AST_NODES: tuple[type[ast.AST], ...] = (
    ast.Expression,
    ast.BinOp,
    ast.UnaryOp,
    ast.Constant,
    ast.Name,
    ast.Load,
    ast.Add,
    ast.Sub,
    ast.Mult,
    ast.UAdd,
    ast.USub,
)
_ALLOWED_NAMES: frozenset[str] = frozenset(("Inflow", "Storage", "nan"))


def _compile_release_expression(expr_text: str, path_hint: str) -> tuple[ast.Expression, float]:
    """Validate and compile a release expression; return (AST, clamp_min)."""
    expr_text = expr_text.strip()
    clamp_min = -math.inf
    if m := _RE_MAX_WRAP.match(expr_text):
        expr_text = m.group(1)
        clamp_min = 0.0
    try:
        tree = ast.parse(expr_text, mode="eval")
    except SyntaxError as exc:
        msg = f"{path_hint}: cannot parse release expr {expr_text!r}: {exc}"
        raise RuleParseError(msg) from exc

    for node in ast.walk(tree):
        if not isinstance(node, _ALLOWED_AST_NODES):
            msg = (
                f"{path_hint}: unsafe AST node {type(node).__name__} in release expr {expr_text!r}"
            )
            raise RuleParseError(msg)
        if isinstance(node, ast.Name) and node.id not in _ALLOWED_NAMES:
            msg = f"{path_hint}: unknown name {node.id!r} in release expr {expr_text!r}"
            raise RuleParseError(msg)
    return tree, clamp_min


def _parse_release_expression(expr_text: str, path_hint: str) -> ReleaseExpr:
    """Parse one of: `<num>`, `max(<expr>, 0)`, or a Python-style affine expr.

    Extracts affine coefficients by evaluating the expression at three probe
    points. Because the expression is validated to be purely affine in
    `Inflow`/`Storage` (plus `nan`), the three-point sampling is exact.
    """
    tree, clamp_min = _compile_release_expression(expr_text, path_hint)
    code = compile(tree, "<release_expr>", mode="eval")
    ns_c = {"Inflow": 0.0, "Storage": 0.0, "nan": math.nan}
    ns_i = {"Inflow": 1.0, "Storage": 0.0, "nan": math.nan}
    ns_s = {"Inflow": 0.0, "Storage": 1.0, "nan": math.nan}
    safe_globals: dict[str, object] = {"__builtins__": {}}
    try:
        c = float(eval(code, safe_globals, ns_c))  # noqa: S307
        v_i = float(eval(code, safe_globals, ns_i))  # noqa: S307
        v_s = float(eval(code, safe_globals, ns_s))  # noqa: S307
    except Exception as exc:
        msg = f"{path_hint}: error evaluating release expr {expr_text!r}: {exc}"
        raise RuleParseError(msg) from exc

    # For NaN-only expressions the subtraction produces NaN, which is the
    # correct propagation semantics: the evaluator returns NaN and predicate
    # comparisons against NaN thresholds yield False, so the branch is inert.
    a_inflow = v_i - c
    a_storage = v_s - c
    return ReleaseExpr(a_inflow=a_inflow, a_storage=a_storage, c=c, clamp_min=clamp_min)


# --- Predicate-list parser ---------------------------------------------------


def _parse_predicate_list(clause: str, path_hint: str) -> tuple[PredicateTriple, ...]:
    """Parse a predicate clause `(V OP N) and (V OP N) ...` into triples.

    An empty or whitespace-only clause (e.g. the bare `()` that appears in
    some Res_M condition files) parses to an empty tuple; callers should
    interpret that as a branch that never matches.
    """
    bare = clause.strip()
    if bare in {"", "()"}:
        return ()
    predicates = tuple(
        PredicateTriple(_VAR_CODES[m.group(1)], _OP_CODES[m.group(2)], float(m.group(3)))
        for m in _RE_PREDICATE.finditer(clause)
    )
    if not predicates:
        msg = f"{path_hint}: no predicates found in clause {clause!r}"
        raise RuleParseError(msg)

    residue = _RE_PREDICATE.sub("", clause)
    residue = re.sub(r"\band\b", "", residue).strip()
    if residue:
        msg = f"{path_hint}: unparsed residue in clause {clause!r}: {residue!r}"
        raise RuleParseError(msg)
    return predicates


# --- File-level parsers ------------------------------------------------------


def parse_module(path: Path | str) -> ModuleDescriptor:
    """Parse one GDROM module file into a typed descriptor.

    Reads the file at ``path``, infers the module kind (EXPR or TREE) from
    its content, and returns a :class:`ModuleDescriptor` carrying the parsed
    release expressions and any branch predicates. The file name must follow
    the upstream convention ``{grand_id}_{module_id}.txt``.

    Parameters
    ----------
    path : pathlib.Path
        Path to a single GDROM module file. The stem must be of the form
        ``{grand_id}_{module_id}`` where both are non-negative integers.
        The file must exist and be readable as UTF-8 text.

    Returns
    -------
    ModuleDescriptor
        Parsed descriptor with ``kind = ModuleKind.EXPR`` (single release
        expression) or ``kind = ModuleKind.TREE`` (ordered predicate-guarded
        branches). The ``grand_id`` and ``module_id`` fields are recovered
        from the file name.

    Raises
    ------
    RuleParseError
        If the file name does not match the ``{grand_id}_{module_id}.txt``
        convention, if the file is empty, if any line is not recognized as a
        valid rule, if a release expression cannot be safely AST-parsed, or
        if a TREE branch uses a predicate variable other than ``Inflow`` or
        ``Storage``.
    FileNotFoundError
        If ``path`` does not exist.

    Examples
    --------
    >>> from pathlib import Path
    >>> mod = parse_module(Path("tests/data/modules/40_0.txt"))
    >>> mod.kind
    <ModuleKind.EXPR: 0>
    >>> round(mod.expr.c, 4)
    35.0377
    """
    path = Path(path)
    if not path.is_file():
        msg = f"module file does not exist: {path}"
        raise FileNotFoundError(msg)
    stem_parts = path.stem.split("_", 1)
    if len(stem_parts) != 2:
        msg = f"{path}: filename must be `{{grand_id}}_{{module_id}}.txt`"
        raise RuleParseError(msg)
    try:
        grand_id = int(stem_parts[0])
        module_id = int(stem_parts[1])
    except ValueError as exc:
        msg = f"{path}: grand_id and module_id must be integers"
        raise RuleParseError(msg) from exc

    lines = [ln.strip() for ln in path.read_text().splitlines() if ln.strip()]
    if not lines:
        msg = f"{path}: file is empty"
        raise RuleParseError(msg)

    first = lines[0]

    # `Release = <expr>` single-line form
    if m := _RE_MODULE_EXPR_RELEASE.match(first):
        if len(lines) != 1:
            msg = f"{path}: `Release = ...` module must have exactly one line"
            raise RuleParseError(msg)
        return ModuleDescriptor(
            grand_id=grand_id,
            module_id=module_id,
            kind=ModuleKind.EXPR,
            expr=_parse_release_expression(m.group(1), str(path)),
        )

    # `Release: <num>` single-line form (constant)
    if (not first.startswith("if")) and (m := _RE_MODULE_CONST_RELEASE.match(first)):
        if len(lines) != 1:
            msg = f"{path}: `Release: ...` module must have exactly one line"
            raise RuleParseError(msg)
        return ModuleDescriptor(
            grand_id=grand_id,
            module_id=module_id,
            kind=ModuleKind.EXPR,
            expr=_parse_release_expression(m.group(1), str(path)),
        )

    # TREE form: one `if (...) then Release: <expr>` per line
    branches: list[ModuleBranch] = []
    for ln in lines:
        m = _RE_TREE_BRANCH.match(ln)
        if not m:
            msg = f"{path}: unrecognized rule line {ln!r}"
            raise RuleParseError(msg)
        preds = _parse_predicate_list(m.group(1), str(path))
        for p in preds:
            if p.var_code not in (VarCode.INFLOW, VarCode.STORAGE):
                msg = (
                    f"{path}: TREE module predicate must use Inflow or Storage only; "
                    f"got var_code={p.var_code}"
                )
                raise RuleParseError(msg)
        release = _parse_release_expression(m.group(2), str(path))
        branches.append(ModuleBranch(preds, release))
    return ModuleDescriptor(
        grand_id=grand_id,
        module_id=module_id,
        kind=ModuleKind.TREE,
        tree_branches=tuple(branches),
    )


def parse_module_condition(path: Path | str) -> ConditionDescriptor:
    """Parse one GDROM dispatcher CART file into a typed descriptor.

    Reads the dispatcher tree at ``path``, which selects a module identifier
    as a function of inflow, storage, the Palmer Drought Severity Index, and
    day of year. The file name must be ``{grand_id}.txt``.

    Parameters
    ----------
    path : pathlib.Path
        Path to a single dispatcher condition file. The stem must be a
        non-negative integer GRanD identifier. The file must exist and be
        readable as UTF-8 text. Empty-predicate branches (``if () then
        module: 0``) are preserved as inert branches, matching the
        truthiness convention of the GDROM authors' reference simulator.

    Returns
    -------
    ConditionDescriptor
        Parsed descriptor with ``grand_id`` recovered from the file name
        and ``branches`` listing each ``(predicates, module_id)`` rule in
        source order.

    Raises
    ------
    RuleParseError
        If the file name does not match the ``{grand_id}.txt`` convention,
        if the file is empty, or if any line is not recognized as a valid
        dispatcher rule.
    FileNotFoundError
        If ``path`` does not exist.

    Examples
    --------
    >>> from pathlib import Path
    >>> cond = parse_module_condition(Path("tests/data/module_conditions/41.txt"))
    >>> cond.grand_id
    41
    >>> len(cond.branches) >= 1
    True
    """
    path = Path(path)
    if not path.is_file():
        msg = f"dispatcher file does not exist: {path}"
        raise FileNotFoundError(msg)
    try:
        grand_id = int(path.stem)
    except ValueError as exc:
        msg = f"{path}: filename must be `{{grand_id}}.txt`"
        raise RuleParseError(msg) from exc

    lines = [ln.strip() for ln in path.read_text().splitlines() if ln.strip()]
    if not lines:
        msg = f"{path}: file is empty"
        raise RuleParseError(msg)

    branches: list[ConditionBranch] = []
    for ln in lines:
        m = _RE_CONDITION_BRANCH.match(ln)
        if not m:
            msg = f"{path}: unrecognized condition line {ln!r}"
            raise RuleParseError(msg)
        preds = _parse_predicate_list(m.group(1), str(path))
        branches.append(ConditionBranch(preds, int(m.group(2))))
    return ConditionDescriptor(grand_id=grand_id, branches=tuple(branches))
